
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    container_name: ENGWEB2024-normal-mongo-seed
    image: mongo:latest
    volumes:
      - /home/asus/projects/EngWeb/ENGWEB2024-Normal/contratos2024.json:/datasets//home/asus/projects/EngWeb/ENGWEB2024-Normal/contratos2024.json

    command: /bin/bash -c "mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets//home/asus/projects/EngWeb/ENGWEB2024-Normal/contratos2024.json --jsonArray"
